defaults:
  - evolution: reg_evolution

model:
  max_learn_length: 10
  max_predict_length: 10

dataset:
  nsamples: 1000
  nfeatures: 2

pool:
  nscalars: 4
  nvectors: 4
  # TODO: add nmatrix

hydra:
  run:
    # dir: ./outputs/circles/penalty/${evolution.type}/population=${evolution.params.population_size}_subset=${evolution.params.subset_size}_cycles=${evolution.params.ncycles}
    dir: ./outputs/moons/penalty/${evolution.type}/population=${evolution.params.population_size}_subset=${evolution.params.subset_size}_cycles=${evolution.params.ncycles}

    # dir: ./outputs/circles_dataset/${evolution.type}/population=${evolution.params.population_size}_subset=${evolution.params.subset_size}_cycles=${evolution.params.ncycles}