defaults:
  - evolution: reg_evolution

dataset:
  nsamples: 1000
  nfeatures: 2

pool:
  nscalars: 4
  nvectors: 4
  # TODO: add nmatrix

hydra:
  run:
    dir: ./outputs/${evolution.type}/population=${evolution.params.population_size}_subset=${evolution.params.subset_size}_cycles=${evolution.params.ncycles}